name:                webdriver-wrapper
version:             0.2.0.0
github:              "gtollini/webdriver-wrapper"
license:             BSD-3-Clause
author:              "Gabriel Tollini"
maintainer:          "gabrieltollini@hotmail.com"
copyright:           "2024 Gabriel Tollini"

extra-doc-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Wrapper around the webdriver package that automatically manages Selenium
category:            browser, selenium, testing, web, webdriver, geckodriver

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gtollini/webdriver-wrapper#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 2.1.2.1 && < 2.3
- bytestring >= 0.11.5 && < 0.13
- filepath >= 1.4 && < 1.6
- text >= 2.0.2 && < 2.2
- unordered-containers >= 0.2.20 && < 0.3
- async >= 2.2.5 && < 2.3
- directory >= 1.3.8 && < 1.4
- extra >= 1.7.16 && < 1.8
- process >= 1.6.18 && < 1.7
- http-conduit >= 2.3.8 && < 2.4
- zlib >= 0.6.3 && < 0.8
- http-types >= 0.12.4 && < 0.13
- process-extras >= 0.7.4 && < 0.8
- retry >= 0.9.3 && < 0.10
- string-interpolate >= 0.3.3 && < 0.4
- tar >= 0.5.1.1 && < 0.7
- webdriver >= 0.12.0 && < 0.13
- zip-archive >= 0.4.3 && < 0.5
- unix >= 2.8.4 && < 2.9 
- vector >= 0.13.1 && < 0.14

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src