name:                webdriver-wrapper
version:             0.1.0.0
github:              "gtollini/webdriver-wrapper"
license:             BSD-3-Clause
author:              "Gabriel Tollini"
maintainer:          "gabrieltollini@hotmail.com"
copyright:           "2024 Gabriel Tollini"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gtollini/webdriver-wrapper#readme>

dependencies:
- base >= 4.7 && < 5
- text
- webdriver
- unordered-containers
- directory
- process
- process-extras
- string-interpolate
- http-conduit
- aeson
- http-types
- bytestring
- tar
- zip-archive
- zlib
- async

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  webdriver-wrapper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webdriver-wrapper
